name: test-release
on:
  release:
    types: [published]
  workflow_dispatch:
  push:
    branches:
      - master
      - develop


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: print event
        run: echo $GITHUB_EVENT_NAME
